### ISSUE TITLE
CUDA cannot be found during installation

### ISSUE THREAD

**Issue by krittaprot** [BatsResearch/bonito#5]
Hello,

I have tried installing the library for this model today but failed due to the following error:

(bonito) C:\Users\kritt\Desktop\Bonito\vllm>pip install -e .
Obtaining file:///C:/Users/kritt/Desktop/Bonito/vllm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      C:\Users\kritt\AppData\Local\Temp\pip-build-env-v3xcni1y\overlay\Lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\'
      Traceback (most recent call last):
        File "C:\Users\kritt\.conda\envs\bonito\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\kritt\.conda\envs\bonito\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\kritt\.conda\envs\bonito\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\kritt\AppData\Local\Temp\pip-build-env-v3xcni1y\overlay\Lib\site-packages\setuptools\build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\kritt\AppData\Local\Temp\pip-build-env-v3xcni1y\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\kritt\AppData\Local\Temp\pip-build-env-v3xcni1y\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\kritt\AppData\Local\Temp\pip-build-env-v3xcni1y\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 446, in <module>
        File "<string>", line 406, in get_vllm_version
      NameError: name 'nvcc_cuda_version' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I already checked/tried the followings:
- CUDA_HOME variable in the system, looked for nvcc.exe and found it in the bin folder. I believe it is already correct.

- Numpy was installed as below:

(bonito) C:\Users\kritt\Desktop\Bonito\vllm>pip install numpy
Requirement already satisfied: numpy in c:\users\kritt\.conda\envs\bonito\lib\site-packages (1.26.4)

- pip install -e . always ended up with this error.
- pip install vllm also ended with the same error.

Can anyone provide guidance on how to resolve this issue?

**Comment by nihalnayak** [comment]
Thanks for posting this issue. This issue originates from the `vllm` package rather than bonito. Linux is a requirement for `vllm`. However, `vllm` works on windows WSL 2. See the following linked issue: https://github.com/vllm-project/vllm/issues/669#issuecomment-1668639720.

**Comment by krittaprot** [comment]
That explains it, thank you.
